corona-school/user-app

src/Navigator.tsx
src/components/Notification/MessageBox.tsx
src/components/Notification/NotificationAlert.tsx
src/components/Notification/NotificationPanel.tsx
src/components/Notification/TimeIndicator.tsx
src/hooks/useConcreteNotification.ts
src/widgets/InAppMessage.tsx

for testing:
- import function into i.e. `Navigator` in a `useEffect` with `setInterval`
- props you need is a `notification` object and `isMobile`
- for `isMobile` use the `useBreakpointValue` hook from `native base`
`const isMobile = useBreakpointValue({
base: true,
lg: false 
})`

InAppMessages component 

---

src/pages/Settings.tsx
src/pages/student/ProfileStudent.tsx

Remove Participation Certificates for now

---

src/Utility.ts
src/widgets/AppointmentCard.tsx

resolves https://github.com/corona-school/project-user/issues/531

Fix time calculation for next meeting

---

src/pages/Helpcenter.tsx

resolves https://github.com/corona-school/project-user/issues/533

Fix contact form

---

src/pages/pupil/Dashboard.tsx
src/pages/pupil/Matching.tsx
src/pages/student/DashboardStudent.tsx
src/pages/student/MatchingStudent.tsx
src/types/lernfair/Match.ts
src/widgets/LearningPartner.stories.mdx
src/widgets/LearningPartner.tsx

resolves https://github.com/corona-school/project-user/issues/540

Contact Match Partner

---

src/pages/registration/Legal.tsx

Closes https://github.com/corona-school/user-app/pull/63 because requirements changed (see message from Nicolas in #publ-allgemein)
Closes https://github.com/corona-school/project-user/issues/534

Changed data processing text, removed USA checks

---

src/NavigatorLazy.tsx
src/pages/pupil/ProfilePupil.tsx
src/pages/student/ProfileStudent.tsx

See https://github.com/corona-school/project-user/issues/538
Also fixed naming of pupil profile to to ProfilePupil be more consistent with ProfilStudent

Removed edit feature from name component of student profile

---

src/hooks/useNotificationPreferences.ts

small api change in https://github.com/corona-school/backend/pull/429 - preferences won't be wrapped in array any longer

Small fix for preferences

---

README.md
linter/typed-gql.js
package-lock.json
package.json

resolves https://github.com/corona-school/project-user/issues/544

Typed gql improvements

---

package-lock.json
src/pages/Registration.tsx
src/pages/registration/Legal.tsx

Also:  removed chunk of unused code
Closes https://github.com/corona-school/project-user/issues/535

Fixed back button in helper registration workflow

---

src/pages/pupil/ProfilePupil.tsx
src/pages/student/ProfileStudent.tsx

By moving the text inputs to their own components, we can prevent the whole page from rerendering on every keystroke

Fix Profile Performance

---

src/modals/DeactivateAccountModal.tsx
src/modals/DissolveMatchModal.tsx
src/pages/pupil/Dashboard.tsx
src/widgets/ImportantInformation.tsx
src/widgets/LearningPartner.tsx

I have added keys for components inside map to avoid warnings

add missing keys

---

src/components/notifications/preferences/MarketingNotifications.tsx
src/components/notifications/preferences/Preferences.tsx
src/components/notifications/preferences/ToggleAll.tsx
src/helper/notification-helper.ts
src/hooks/useLayoutHelper.ts
src/hooks/useNotificationPreferences.ts
src/lang/notification/de.ts
src/pages/notification/NotficationControlPanel.tsx

Buttons to activate and deactivate all switches in Marketing Notifications

Feat/LF-76 activate/deactivate all 

---

src/App.tsx
src/Navigator.tsx
src/components/notifications/MessageBox.tsx
src/hooks/useConcreteNotifications.ts

Notification is now clickable and navigation resolves internal and external routes

LF-33 notification link

---

.github/workflows/deploy-storybook.yml
.github/workflows/verify-prod.yml
src/widgets/ImportantInformation.tsx

resolves https://github.com/corona-school/project-user/issues/545

Add Remission Request Download

---

src/components/notifications/preferences/ToggleAll.tsx

some minor style changes to the newsletter settings button.

Style changes newsletter button

---

src/components/notifications/MessageBox.tsx
src/helper/notification-preferences.ts
src/hooks/useConcreteNotification.ts
src/hooks/useConcreteNotifications.ts
src/types/lernfair/Notification.ts

minor change because of field renaming in https://github.com/corona-school/backend/pull/455

LF-60 update query

---

src/NavigatorLazy.tsx
src/components/WithNavigation.tsx
src/helper/appointment-helper.ts
src/lang/appointment/de.ts
src/pages/Appointments.tsx
src/types/lernfair/Appointment.ts
src/widgets/FloatingActionButton.stories.mdx
src/widgets/FloatingActionButton.tsx
src/widgets/appointment/Appointment.tsx
src/widgets/appointment/AppointmentList.stories.mdx
src/widgets/appointment/AppointmentList.tsx
src/widgets/appointment/AppointmentTile.stories.mdx
src/widgets/appointment/AppointmentTile.tsx
src/widgets/appointment/CalendarMonth.tsx
src/widgets/appointment/CalendarWeek.tsx
src/widgets/appointment/CalendarYear.tsx
src/widgets/appointment/dummy/appointments.ts
src/widgets/appointment/dummy/testdata.ts
src/widgets/appointment/testdata.ts

todo: some mini stylings and - maybe - renaming 😄

Appointment list

---

src/components/modal/DeleteAppointmentModal.stories.mdx
src/components/modal/DeleteAppointmentModal.tsx
src/lang/appointment/de.ts

**Storybook**: Modal to delete an appointment!

Delete appointment modal

---

src/pages/pupil/Matching.tsx
src/pages/student/MatchingStudent.tsx

Resolves: corona-school/project-user#564

Add: active matches first on pupils and students

---

src/pages/SingleCourse.tsx

Field alreadyPromoted is fetched conditionally only if user is Student. 
Refactoring on condition-checking functions and rendering

LF-117 query

---

src/components/HeaderCard.tsx
src/lang/course/de.ts
src/pages/CreateCourse.tsx
src/pages/Helpcenter.tsx
src/pages/OnboardingTourList.tsx
src/pages/RequestCertificate.tsx
src/pages/Settings.tsx
src/pages/SingleCourse.tsx
src/pages/change-setting/ChangeSettingLanguage.tsx
src/pages/change-setting/ChangeSettingSchoolClass.tsx
src/pages/change-setting/ChangeSettingSchoolType.tsx
src/pages/change-setting/ChangeSettingState.tsx
src/pages/change-setting/ChangeSettingSubject.tsx
src/pages/notification/NotficationControlPanel.tsx
src/pages/pupil/Matching.tsx
src/pages/pupil/ProfilePupil.tsx
src/pages/pupil/matching_new/RequestMatch.tsx
src/pages/student/CertificateDetails.tsx
src/pages/student/MatchingStudent.tsx
src/pages/student/matching_new/RequestMatch.tsx

fix stacking and add the notification bell to any page!

Fix button stacking

---

src/pages/student/StudentGroup.tsx

Resolves: corona-school/project-user#559

Fix: exlcude past courses from the course tab

---

src/pages/change-setting/ChangeSettingLanguage.tsx
src/types/lernfair/Language.ts

Closes https://github.com/corona-school/project-user/issues/571

Fixed umlauts in language names

---

src/widgets/ImportantInformation.tsx

Resolves: corona-school/project-user#520

Fix: tuned condition of welcome message appearance

---

src/pages/student/DashboardStudent.tsx

resolves https://github.com/corona-school/project-user/issues/560

Only show relevant sections for students on dashboard

---

src/lang/matching/de.ts
src/pages/CreateCourse.tsx
src/pages/course-creation/CourseAppointments.tsx
src/pages/student/StudentGroup.tsx

resolves https://github.com/corona-school/project-user/issues/562
resolves https://github.com/corona-school/project-user/issues/577

Fix course creation file upload, time picker and show other courses to instructors

---

src/lang/course/de.ts
src/modals/AddCourseInstructor.tsx

The search now only finds exact matches for privacy reasons, thus the UI is adapted accordingly, i.e. no multi-select, and clear hints for the search
resolves https://github.com/corona-school/project-user/issues/581

Adapt instructor search to changed search behaviour

---

src/lang/dashboard/de.ts
src/pages/student/DashboardStudent.tsx

resolves https://github.com/corona-school/project-user/issues/580

Remove open match request count from dashboard

---

src/widgets/ImportantInformation.tsx

resolves https://github.com/corona-school/project-user/issues/579

Only show buttons the user is permissioned to use in Welcome message

---

src/web/scss/index.scss

resolves https://github.com/corona-school/project-user/issues/568

Show scrollbar on large screens

---

README.md
src/hooks/useApollo.tsx

resolves https://github.com/corona-school/project-user/issues/583

Improve temporary session

---

src/lang/appointment/de.ts
src/pages/CreateAppointment.tsx
src/pages/create-appointment/AppointmentAssignment.tsx
src/pages/create-appointment/AppointmentsInsight.tsx
src/widgets/appointment/create-appointment/GroupTile.tsx

for now: can't query match appointments, thats why we skip step two at the moment.

Subtitle for step two

---

src/pages/NoAcceptRegistration.tsx
src/pages/student/matching_new/German.tsx
src/widgets/ImportantInformation.tsx

- Adapt link in registration rejection
- Fix Button in Match Request
- Fix interest confirmation (resolves https://github.com/corona-school/project-user/issues/588)

Various small fixes

---

src/lang/notification/de.ts

added new texts for informationsdetails about e-mail notifications.

New e-mail notification info texts

---

src/widgets/ImportantInformation.tsx

By making them slightly smaller it is hopefully mor obvious to the user that there are multiple important notifications

Show configurable important notification first, 97% width

---

src/pages/SingleCourse.tsx

Frontend part of https://github.com/corona-school/project-user/issues/566

Disable promotion and editing if course has already finished

---

src/lang/course/de.ts
src/lang/matching/de.ts
src/pages/student/CourseGroups.tsx
src/pages/student/StudentGroup.tsx

New tabs '**Meine Kurse**' and '**Alle Kurse**'

New subcourse grouping

---

src/pages/Registration.tsx
src/pages/registration/Legal.tsx

refers to [Set newsletter preferences on registration]( https://github.com/corona-school/backend/pull/507) #507

Change newsletter subscription

---

src/User.tsx
src/hooks/useApollo.tsx
src/lang/login/de.ts
src/pages/Login.tsx
src/pages/LoginToken.tsx
src/pages/Registration.tsx
src/pages/ResetPassword.tsx
src/pages/VerifyEmail.tsx
src/pages/Welcome.tsx

- Removed session handling from components
- Moved it to `useApollo` hook
- Added Alert in case of invalid token
Fixes
- https://github.com/corona-school/project-user/issues/578
- https://github.com/corona-school/project-user/issues/584

Refactored session handling

---

package-lock.json
package.json
src/lang/login/de.ts
src/pages/Login.tsx
src/pages/registration/PersonalData.tsx

- added package [validator.js](https://github.com/validatorjs/validator.js) instead of `class-validator` because `class-validator` uses `validator.js` under the hood
- added validation to `Login.tsx` and used the FormErrors
- refactored `PersonalData.tsx` to use the same validation as `Login.tsx`
- added translation text
Fixes:
- https://github.com/corona-school/project-user/issues/645

Handle invalid mails during login

---

src/pages/course-creation/CourseClassification.tsx

Issue  #597
https://github.com/corona-school/project-user/issues/597#issuecomment-1489159727

Reset course tags on course category change

---

src/widgets/certificates/SelectedPupilWizard.tsx

```js
parseInt("10,5") -> 10
+"10,5" -> NaN
parseInt("10h") -> 10
+"10h" -> NaN
```

Use parseInt consistently

---

src/pages/SingleMatch.tsx
src/pages/match/Matches.tsx
src/pages/pupil/Matching.tsx
src/pages/student/MatchingStudent.tsx
src/widgets/LearningPartner.tsx

- the buttons should only be available until the `"new videochat"` is integrated
- buttons on `SingleMatch` page are `disabled` for now

Re-activate match buttons

---

src/widgets/certificates/SelectedPupilWizard.tsx

resolves https://github.com/corona-school/project-user/issues/671

Allow all subjects to be selected during certificate request

---

src/lang/dashboard/de.ts
src/lang/matching/de.ts
src/modals/RecommendModal.tsx
src/pages/SingleMatch.tsx
src/pages/match/MatchPartner.tsx
src/widgets/LearningPartner.tsx

Fixes from comments on:
- https://github.com/corona-school/project-user/issues/662
- https://github.com/corona-school/project-user/issues/661
- https://github.com/corona-school/project-user/issues/563

Fixes: match card and details, recommend link

---

src/lang/helperwizard/de.ts

Typo from support.

---

src/lang/lernfair/de.ts
src/lang/single/de.ts
src/pages/pupil/single-course/PupilCourseButtons.tsx

Resolves second part of https://github.com/corona-school/project-user/issues/667

Add: check if joinSubcourse() failed + if pupil is already a participant

---

src/pages/student/onboarding/GroupOnboarding.tsx
src/pages/student/onboarding/MatchOnboarding.tsx
src/widgets/OnboardingCard.tsx

fixes [issue](https://github.com/corona-school/project-user/issues/561) @tobiasbork

remove image texts from onboarding cards

---

src/pages/pupil/Dashboard.tsx

fixes [issue](https://github.com/corona-school/project-user/issues/595#issuecomment-1510440362) @tobiasbork

add new card design to start page

---

src/hooks/useApollo.tsx

To make the application more secure we want to finally retire the old token login mechanism. We'll keep both query parameter for now.

refactor: retire loginLegacy

---

src/components/FilePicker.tsx

As discussed here https://github.com/corona-school/backend/pull/645

refactor(file-upload): update upload file size from 5mb -> 10mb

---

src/components/chat/ChatInbox.tsx
src/components/chat/NewChat.tsx
src/context/ChatContext.tsx
src/pages/Chat.tsx

feat: chat context and hook

---

src/pages/pupil/SingleCoursePupil.tsx
src/pages/pupil/single-course/PupilCourseButtons.tsx

- add button for course prospects to contact the course instructor
- only show button if prospect contact is allowed

feat: contact instructor as prospect

---

src/components/appointment/Buttons.tsx
src/lang/appointment/de.ts
src/pages/Appointments.tsx
src/pages/CreateAppointment.tsx
src/pages/CreateCourseAppointment.tsx
src/pages/EditAppointment.tsx
src/pages/create-appointment/AppointmentAssignment.tsx
src/pages/create-appointment/AppointmentCreation.tsx
src/pages/create-appointment/AppointmentForm.tsx
src/pages/edit-appointment/AppointmentEdit.tsx
src/web/scss/components/DatePicker.scss
src/widgets/AddAppointmentButton.tsx
src/widgets/InputSuffix.tsx
src/widgets/appointment/AppointmentDate.tsx
src/widgets/appointment/AppointmentDay.tsx
src/widgets/appointment/AppointmentTile.tsx

- show back button on navigation https://github.com/corona-school/project-user/issues/768
- readonly list doesnt show current appointments anymore https://github.com/corona-school/project-user/issues/764
- dont show loading spinner when appointments are loading https://github.com/corona-school/project-user/issues/767
- changes on edit page https://github.com/corona-school/project-user/issues/769
- adjust add button placement https://github.com/corona-school/project-user/issues/773
- rename load past appointments https://github.com/corona-school/project-user/issues/770
- routing back to "rootpath" https://github.com/corona-school/project-user/issues/772
- order of group assignment on appointment creation https://github.com/corona-school/project-user/issues/776
- disable delete past …

fix: appointment bugs

---

src/helper/appointment-helper.ts
src/lang/single/de.ts
src/pages/SingleMatch.tsx
src/pages/create-appointment/AppointmentCreation.tsx
src/pages/edit-appointment/AppointmentEdit.tsx
src/pages/edit-appointment/AppointmentEditForm.tsx
src/pages/pupil/Dashboard.tsx
src/pages/student/DashboardStudent.tsx
src/widgets/AppointmentCard.tsx

- added my appointments to dashboard query
- adjusted `AppointmentCard`
- integrated zoom meeting
- fix validation of min five min later for match appointments
- added min value to edit appointment date input

feat: show my next appointment on dashboard

---

src/components/ZoomMeeting.tsx
src/components/appointment/AppointmentDetail.tsx
src/helper/appointment-helper.ts
src/pages/SingleMatch.tsx
src/pages/chat/LeftVideoChat.tsx
src/pages/create-appointment/AppointmentCreation.tsx
src/widgets/appointment/AppointmentTile.tsx

- fixed removing styles when an error happens
- navigating back where I came from when canceling a meeting
- button width on desktop
- refetching timing issue when creating an appointment

fix: various appointment fixes

---

src/components/appointment/AppointmentDetail.tsx
src/pages/Appointment.tsx
src/pages/SingleMatch.tsx

- add a `refetching query` if an appointment was dissolved or cancelled

fix: refetch data after decline or cancel appointment

---

src/pages/create-appointment/AppointmentAssignment.tsx

Only courses with old dates were displayed.

Fix: courses on appointment creation

---

src/pages/pupil/SingleCoursePupil.tsx
src/pages/pupil/single-course/PupilCourseButtons.tsx
src/pages/student/SingleCourseStudent.tsx

Problem: A student couldn't start the meeting even though the class started in less than 30 minutes.
`isOrganizer` was undefined

fix: enable video button

---

src/modals/Unsplash.tsx
src/pages/course-creation/CourseAppointments.tsx
src/pages/student/single-course/StudentCourseButtons.tsx

This can happen if a user deletes all lectures after the course has been created. The problem is that the course is not editable anymore and the user-app just crashes.
This PR will make sure that this doesn't happen anymore.
https://lern-fair.slack.com/archives/C03E45MES4X/p1689785056516519

fix: courses without lectures

---

src/components/appointment/AppointmentDetail.tsx

refers to: https://github.com/corona-school/project-user/issues/846

fix: users can decline appointments multiple times

---

src/components/appointment/AppointmentDetail.tsx
src/components/appointment/Buttons.tsx
src/lang/appointment/de.ts

refers to: https://github.com/corona-school/backend/pull/787

fix: prevent deletion of last appointment

---

.github/workflows/main-barrier.yml
Procfile
package-lock.json
package.json
scripts/build.js
scripts/dd-upload-source-maps.sh
src/config.ts
src/index.tsx
src/types/react-app-env.d.ts

There are a couple of environment variables that have to be set in staging/production:
* `DATADOG_API_KEY` & `DATADOG_SITE` to upload the source maps
* `RUNTIME_DD_ENV` to distinguish the environments within DataDog
* `RUNTIME_DD_CLIENT_TOKEN` & `RUNTIME_DD_APP_ID` to authenticate RUM 
Besides that we have to enable the `runtime-dyno-metadata` lab for all user-apps and backend environments.

feature: install DD real-user-monitoring

---

src/lang/screening/de.ts
src/pages/screening/Dashboard.tsx
src/types/index.ts
src/widgets/matching/MatchStudentCard.tsx
src/widgets/screening/ScreenPupilCard.tsx

- Refresh Data when navigating between Tabs in Screening
- Show the correct dissolve date in the MatchStudentCard
- Order Matches on the Screening Tab
- If multiple users have the same name, all are shown
- Add note to deactivated accounts

Various screening bugs

---

src/components/BottomNavigationBar.tsx
src/components/SideBarMenu.tsx
src/context/ChatContext.tsx

feat: disable chat for screener

---

src/pages/student/SingleCourseStudent.tsx

fix: action on rejected courses

---

src/components/ContactSupportForm.tsx
src/lang/chat/de.ts
src/modals/ContactSupportModal.tsx
src/pages/Chat.tsx

feat: DSGVO for report message

---

package-lock.json
package.json

The changelog looks promising:
- "Webinar attendees could not receive audio on mobile Safari."
- "Fixed an issue where occasionally iOS Safari browser crashes and refreshes."

Update Zoom WebSDK

---

src/pages/Chat.tsx

fix: leave specific chat

---

src/context/ChatContext.tsx

Add missing effect dependency, which caused the effect to not reload properly when the user is logged in before the user info is determined (i.e. when the session expired).
Also documents the different preconditions

fix: Chat Load when Session Expired

---

src/pages/CreateCourse.tsx

resolves https://github.com/corona-school/project-user/issues/877

fix: Add instructors during course creation

---

src/components/appointment/AppointmentMetaDetails.tsx
src/lang/course/de.ts
src/pages/student/single-course/StudentCourseButtons.tsx
src/widgets/AppointmentCard.tsx
src/widgets/AppointmentDay.tsx

increase `join before minutes` to 4 hours instead of 30 minutes

fix: increase time to join meeting before

---

src/pages/Chat.tsx

With the DD privacy exclusion the layout was broken.

fix: Chat Layout

---

src/pages/screening/Dashboard.tsx
src/types/index.ts
src/widgets/screening/PupilScreeningCard.tsx
src/widgets/screening/ScreenPupilCard.tsx

- Screeners can create Screenings in case pupils show up in the meeting without having an open screening
- Screeners can see who screened the pupil

feat: Screening improvements

---

src/pages/screening/Dashboard.tsx
src/widgets/screening/ScreenPupilCard.tsx
src/widgets/screening/ScreeningSuggestionCard.tsx

resolves https://github.com/corona-school/project-user/issues/927
resolves https://github.com/corona-school/project-user/issues/929

feat: Screener suggestions, Layout improvements, Quick Suggestion Buttons

---

src/Utility.ts
src/widgets/AppointmentCard.tsx

Fix argument oder of toTimerString invocation, improve days>7 string to show actual date if time is in the week after next week.

Fix argument oder of toTimerString invocation, improve days>7 string

---

src/pages/Appointments.tsx
src/pages/Settings.tsx

Resolves https://github.com/corona-school/project-user/issues/931

feat(screening-dashboard): hide notification panel

---

src/lang/single/de.ts
src/modals/RemoveParticipantFromCourseModal.tsx
src/pages/student/SingleCourseStudent.tsx
src/pages/subcourse/ParticipantRow.tsx
src/types/lernfair/Course.ts

feature: allow course instructors to remove pupils from course

---

src/pages/pupil/SingleCoursePupil.tsx
src/pages/pupil/single-course/PupilCourseButtons.tsx

Also refactor the components by moving dependencies down into the component that needs it.
resolves https://github.com/corona-school/project-user/issues/835

fix: Hide Waitinglist if pupil cannot join waitinglist

---

serve.js
src/lang/welcome/de.ts
src/pages/Welcome.tsx

Support redirecting all users to the same domain. That way we ensure users do not continue to use legacy domains that might be deprovisioned one day.
resolves https://github.com/corona-school/project-user/issues/830

feat: Redirect to main Domain

---

src/lang/matching/de.ts
src/pages/pupil/matching/Details.tsx
src/pages/pupil/matching/German.tsx
src/pages/pupil/matching/Priority.tsx
src/pages/pupil/matching/Subjects.tsx
src/pages/pupil/matching/UpdateData.tsx
src/widgets/NextPrevButtons.tsx
src/widgets/YesNoSelector.tsx

Just some missing translation strings I noticed whilst working on another issue.

i18next strings for pupil matching

---

src/pages/pupil/matching/Details.tsx
src/pages/pupil/matching/German.tsx
src/pages/pupil/matching/RequestMatch.tsx

Resolves https://github.com/corona-school/project-user/issues/957
Not the most beautiful solution, but it works. And as the whole flow is kinda hardcoded atm it doesn't make much sense to overengineer it.

fix: back button leading to forbidden page

---

src/components/VideoButton.tsx
src/components/appointment/AppointmentDetail.tsx
src/components/appointment/AppointmentMetaDetails.tsx
src/pages/Appointment.tsx
src/pages/Appointments.tsx
src/pages/SingleMatch.tsx
src/pages/create-appointment/AppointmentsInsight.tsx
src/pages/pupil/Dashboard.tsx
src/pages/pupil/SingleCoursePupil.tsx
src/pages/pupil/single-course/PupilCourseButtons.tsx
src/pages/student/DashboardStudent.tsx
src/pages/student/SingleCourseStudent.tsx
src/pages/student/single-course/StudentCourseButtons.tsx
src/types/lernfair/Appointment.ts
src/widgets/AppointmentCard.tsx
src/widgets/AppointmentDay.tsx
src/widgets/AppointmentList.tsx
src/widgets/AppointmentTile.tsx
src/widgets/NextAppointmentCard.tsx

This reverts commit 61ba688bcd57f93f4878afa4b3d105940ff568ce.

HOTFIX: Revert "Add support for meeting link overrides (#381)"

---

src/lang/de.json
src/pages/Settings.tsx

what was done:
- the progress page can now be reached via the settings page navigation

Feat: progress in settings

---

src/lang/de.json
src/pages/pupil/matching/Details.tsx
src/pages/pupil/matching/German.tsx
src/pages/pupil/matching/RequestMatch.tsx
src/pages/pupil/matching/Subjects.tsx

Closes https://github.com/corona-school/project-user/issues/1069

1069 fix daz matching userflow

---

src/lang/de.json
src/pages/SingleMatch.tsx

https://github.com/corona-school/project-user/issues/951

feat: Remove E-Mail Contact

---

src/lang/de.json
src/pages/create-appointment/AppointmentAssignment.tsx
src/pages/pupil/Dashboard.tsx
src/pages/pupil/Matching.tsx
src/pages/student/DashboardStudent.tsx
src/pages/student/MatchingStudent.tsx
src/types/lernfair/Match.ts
src/widgets/ImportantInformation.tsx

Completely overlooked those :/

fix: Remove further usages of Match partner email

---

src/pages/pupil/matching/German.tsx
src/pages/pupil/matching/RequestMatch.tsx
src/pages/pupil/matching/Subjects.tsx

Closes https://github.com/corona-school/project-user/issues/1080

Skip subject prio page if only one subject selected

---

src/NavigatorLazy.tsx
src/components/achievements/modals/NextStepModal.tsx
src/pages/ConfirmCertificate.tsx
src/widgets/ImportantInformation.tsx
src/widgets/certificates/ConfirmCertificate.tsx

Add a new page to confirm details for the certificate
- Closes https://github.com/corona-school/project-user/issues/1059

feat: confirm certificate page

---

src/pages/Settings.tsx
src/widgets/Hello.tsx

resolves https://github.com/corona-school/project-user/issues/1096

feat: Remove useless queries

---

src/lang/de.json
src/widgets/ImportantInformation.tsx

https://github.com/corona-school/project-user/issues/972

feat: Also show Important Information for unscreened pupils

---

src/pages/pupil/Dashboard.tsx

Also move it further to the top

feat: Only show Homeworkhelp to screened pupils

---

src/components/achievements/AchievementImageContainer.tsx
src/components/achievements/achievementCard/AchievementCard.tsx
src/components/achievements/achievementCard/CardProgressDescription.tsx
src/components/achievements/modals/AchievementModal.tsx
src/components/achievements/nextStepsCard/NextStepsCard.tsx
src/components/achievements/progressIndicators/IndicatorBar.tsx
src/components/achievements/progressIndicators/IndicatorBarWithSteps.tsx
src/components/achievements/streak/StreakCard.stories.mdx
src/components/achievements/streak/StreakCard.tsx
src/components/achievements/streak/StreakImage.tsx
src/components/achievements/streak/StreakImageContainer.tsx
src/helper/achievement-helper.ts
src/modals/AchievementMessageModal.tsx
src/widgets/AchievementProgress.tsx
src/widgets/ImportantInformation.tsx

closes https://github.com/corona-school/project-user/issues/1119
- a new variable was introduced to the achievements components
- some processing in achievement components was changes

feat: new achievement variable processing

---

src/lang/de.json
src/widgets/ImportantInformation.tsx

https://github.com/corona-school/project-user/issues/972

feat: Different important information for first pupil screening

---

src/pages/pupil/SingleCoursePupil.tsx
src/pages/pupil/single-course/PupilCourseButtons.tsx

-Unified Spacing between SingleCourseStudent and SingleCoursePupil
-Adjusted banner layout

Fix: floating on course detail page 

---

src/lang/de.json
src/pages/student/SingleCourseStudent.tsx

Allow instructors to contact other course instructors via the prospect chat.
resolves https://github.com/corona-school/project-user/issues/1134

feat: Prospect Chat for Instructors

---

src/User.tsx
src/lang/de.json
src/modals/ChatContactSupportModal.tsx
src/modals/ContactSupportModal.tsx
src/modals/RequireScreeningModal.tsx
src/pages/Chat.tsx
src/pages/Registration.tsx
src/pages/VerifyEmail.tsx
src/widgets/SubjectSelector.tsx
src/widgets/screening/EditSubjectsModal.tsx
src/widgets/screening/ScreenPupilCard.tsx

resolves https://github.com/corona-school/project-user/issues/1140
resolves https://github.com/corona-school/project-user/issues/1139

feat: Blocking modal for initial screening, skip verify email

---

src/config.ts
src/types/react-app-env.d.ts
src/widgets/ImportantInformation.tsx

resolves https://github.com/corona-school/project-user/issues/1130

feat: Frontend feature toggle for Gamification

---

src/widgets/HSection.tsx

fix: Wrapping of HSection

---

src/components/VideoButton.tsx
src/pages/SingleMatch.tsx

... so that we can reward gamification achievements.
picked from #420

feat: Track Meeting Joins

---

src/config.ts
src/pages/Settings.tsx
src/types/react-app-env.d.ts

feat: Gamification feature toggle & Link from Settings

---

src/components/achievements/modals/AchievementModal.tsx
src/components/achievements/modals/NextStepModal.tsx

feat: UI Touchups

---

src/widgets/AchievementProgress.tsx

refactor: Use actionName computed from backend

---

src/components/appointment/AppointmentDetail.tsx
src/pages/Appointment.tsx

refactor: Remove unused matchId param

---

src/helper/important-information-helper.ts
src/lang/de.json
src/modals/SuccessModal.tsx
src/pages/CertificateOfConduct.tsx
src/widgets/ImportantInformation.tsx
src/widgets/certificates/CertificateConfirmationBox.tsx

Rework the important information to use the next step card, to be visually on par with achievements.
Also use the new CoC page.
Picked from #420
resolves https://github.com/corona-school/project-user/issues/1040

feat: Use NextSteps Card

---

src/lang/de.json
src/modals/ContactSupportModal.tsx
src/modals/RequireScreeningModal.tsx

fix: Mandatory screening touchups

---

src/User.tsx
src/hooks/useApollo.tsx
src/pages/Login.tsx

When using a secret token to loign (E-Mail / verifiction / etc.) you should get a device token as well. Otheriwse, the user will be logged out automatically every day.

fix: always generate device token

---

src/widgets/ImportantInformation.tsx

This PR is temporarily removing achievements from the important informations section.
We'll reimplement the feature in a different way in the future.

feature: remove achievement related important notification for now

---

src/components/achievements/modals/AchievementModal.tsx
src/modals/AchievementMessageModal.tsx
src/pages/Progress.tsx
src/widgets/AchievementProgress.tsx
src/widgets/ImportantInformation.tsx

feature: use new achievement text mappings

---

src/components/achievements/achievementCard/AchievementCard.tsx
src/widgets/AchievementProgress.tsx

This will ensure that the proper text is displayed here

fix: small achievement ui improvements

---

src/components/achievements/modals/AchievementModal.tsx

Some small adaption for things that we noticed during our last testing session

fix: achievement release changes

---

src/lang/de.json
src/pages/registration/Legal.tsx

Closes https://github.com/corona-school/project-user/issues/1171

Update privacy agreement text during registration

---

src/lang/de.json

Updated title and text of success message

Updated Success Message for SuS Request Creation

---

src/Theme.ts
src/components/TextInputWithSuggestions.tsx
src/pages/screening/Dashboard.tsx
src/types/index.ts
src/widgets/screening/EditLanguagesModal.tsx
src/widgets/screening/ScreenPupilCard.tsx

https://github.com/corona-school/project-user/issues/1179
- Added a control for the knows from on the pupil screening
- Re-styled a bit the TextInputWithSuggestions
- Added labels to edit language/grades/subjects
Backend PR [here](https://github.com/corona-school/backend/pull/1069)

feature: Add knows from field for sus screenings

---

src/components/SubjectTag.tsx
src/modals/AddPupilModal.tsx
src/modals/RemoveParticipantFromCourseModal.tsx
src/pages/SingleMatch.tsx
src/pages/create-appointment/AppointmentAssignment.tsx
src/pages/match/MatchPartner.tsx
src/pages/match/Matches.tsx
src/pages/pupil/SingleCoursePupil.tsx
src/pages/single-course/Waitinglist.tsx
src/pages/student/DashboardStudent.tsx
src/pages/student/MatchingStudent.tsx
src/pages/student/SingleCourseStudent.tsx
src/pages/subcourse/ParticipantRow.tsx
src/types/lernfair/Course.ts

https://github.com/corona-school/project-user/issues/1194
There were some extra places we missed on the ticket description and on the initial testing phase 😅.
[Backend PR here](https://github.com/corona-school/backend/pull/1077)

Feat: Adjust grade label on more places

---

src/helper/notification-preferences.ts

https://github.com/corona-school/project-user/issues/1210
Move some "System" notifications to "Newsletter"
[Backend PR here](https://github.com/corona-school/backend/pull/1084)

feat: Update newsletter categories

---

src/pages/screening/single-course/ScreenerCourseButtons.tsx

Refactor if- to switch-statement in courseState info text

refactor if- to switch-statement in courseState info text

---

src/pages/student/SingleCourseStudent.tsx

Allowing students to edit & delete appointments of their unpublished courses

Allow editing/deleting of unpublished course's appointments

---

src/pages/student/SingleCourseStudent.tsx
src/widgets/PromoteBanner.tsx

https://github.com/corona-school/project-user/issues/1207
- Use new fields for showing the promotion banner
- Add loading state to PromotionBanner
https://github.com/corona-school/backend/pull/1086

feat: Update promotion logic with new fields

---

src/lang/de.json
src/pages/screening/Dashboard.tsx
src/types/index.ts
src/widgets/screening/ScreenStudentCard.tsx

https://github.com/corona-school/project-user/issues/1023
- Display CoC information on the screening tool

feat: Show certificate of conduct information on screening tool

---

src/lib/WebPush.ts

The public key is base64url encoded, not base64 ...

fix: WebPush Key decoding

---

src/config.ts
src/index.tsx
src/types/react-app-env.d.ts

Allow features to be gradually enabled for a random subset of users, which can gradually be increased.
Participants are tracked via Datadog RUM, to be able to identify issues with new features.
resolves https://github.com/corona-school/project-user/issues/1238

feat: Gradual rollout of new features

---

src/components/ContactSupportForm.tsx
src/components/HeaderCard.tsx
src/components/IFrame.tsx
src/components/SideBarMenu.tsx
src/components/Tabs.tsx
src/components/WithNavigation.tsx
src/pages/CreateAppointment.tsx
src/pages/ForPupils.tsx
src/pages/ForStudents.tsx
src/pages/Helpcenter.tsx
src/pages/Settings.tsx
src/pages/create-appointment/AppointmentCreation.tsx
src/pages/create-appointment/AppointmentsInsight.tsx
src/pages/pupil/matching/RequestMatch.tsx
src/pages/student/matching/RequestMatch.tsx
src/routing/NavigatorLazy.tsx
src/widgets/AppointmentList.tsx

https://github.com/corona-school/project-user/issues/1244
- Fixed unneeded scrolls on many pages
- Adjusted iframes styling to take the available page space when desired

Feat: UI improvements

---

src/lang/de.json
src/lang/en.json

EN: Updated labels that were with small caps or complete mambojumbo, e.g. for button labels.
DE: Substituted the label "Lernunterstützung" for "Nachhilfe" in all instances (but 2), since this is the new wording.

text: Use Nachhilfe and Improve English translations

---

src/pages/create-appointment/AppointmentsInsight.tsx

https://github.com/corona-school/project-user/issues/1250
- Fixed `useEffect` that was causing an infinite loop on the appointment list

Fix: Appointment list

---

src/components/BottomNavigationBar.tsx
src/components/SideBarMenu.tsx

Accidentally dropped a few negations ...

fix: Navbar permissions

---

src/lang/de.json

Updated button text for Important Cards - and text for Buttons for Führungszeugnis modal.

texts: Improve German translations

---

src/context/ChatContext.tsx

https://github.com/corona-school/project-user/issues/1231
Added language to the user options that we pass to talkJS

feat: Add language to user chat options

---

src/lang/ar.json

Updated three values for arabic that were missing in the Weglot project.

Texts: Add missing values in Arabic

---

src/pages/pupil/Matching.tsx
src/pages/student/MatchingStudent.tsx

https://github.com/corona-school/project-user/issues/1241
- Fixed unnecessary margin titles on large screens
- Show success messages when canceling a match request
- Fixed spacing on the dissolved request counter
- Moved the request button to the active matches tab

Fix: Matching page UI issues

---

package.json
src/widgets/AlertMessage.tsx

AlertMessage: set status of <Alert /> to "info". So the colorScheme for "info" is also used for the <Alert.Icon />
Resolves corona-school/project-user#1269

Update AlertMessage to use blue icon for informational content

---

linter/typed-gql.js

Change path operation so that split of path separator works also for windows systems

Change path operation so that split of path separator works also for windows systems

---

src/pages/Chat.tsx

Chat.tsx: at session.createInbox set prop enterSendsMessage to false, to allow multiline messages.
Resolves corona-school/project-user#1260

Set prop enterSendsMessage to false, to allow multiline messages

---

src/modals/RequireScreeningModal.tsx

https://github.com/corona-school/project-user/issues/1274
- Added page title to the `RequireScreeningModal`

feat: Add page title to RequireScreeningModal

---

src/lang/de.json

Updated Text for
- New Topic selection, updated title and subtitle, to make it clearer how the waiting time changes for users
- navigation label from "Fortbildung" to "Wissens-Center" 
- renamed "App-Mitteilung" to "Geräte-Mitteilung", to make it clearer that permissions and experience is based on the device

Texts: Improve translations

---

src/lang/de.json

Added two new labels
- school found
- no school found

Text: Improve School search translations

---

src/Theme.ts
src/hooks/useExternalSchoolSearch.ts
src/pages/registration/SchoolSearch.tsx

- Adjust placeholder color
- Adjust school selection visual behavior
- Adjust buttons positioning
- Hide list when a school is selected
- Add page title on the school search step

Feat: School search improvements

---

src/lang/de.json

since search is sometimes not working 100% I used the text below to explain how to improve the search results.

Update text school search tips

---

src/lib/WebPush.ts
src/service-worker-proxy.ts

resolves https://github.com/corona-school/project-user/issues/1285

fix: Worker Registration

---

src/components/Tag.tsx
src/pages/CreateCourse.tsx
src/pages/subcourse/SubcourseData.tsx

- Minor styling adjustments
- Blank page after creating a course page
- Error when opening a course page detail

Fix: Errors on course page

---

src/components/Modal.tsx
src/context/InstallationProvider.tsx
src/lang/ar.json
src/lang/de.json
src/lang/en.json
src/lang/ru.json
src/lang/tr.json
src/lang/uk.json
src/widgets/InstallAppBanner.tsx

https://github.com/corona-school/project-user/issues/1338
- Updated old instructions component with new info modal

Feat: Info modal for iOS

---

src/modals/AdHocMeetingModal.tsx
src/modals/ZoomMeetingModal.tsx

https://github.com/corona-school/project-user/issues/1229

feat: Open zoom meetings in a new tab

---

.env.template
src/components/SearchBar.tsx
src/components/UnsplashPagination.tsx
src/modals/Unsplash.tsx
src/pages/course-creation/CourseBasics.tsx
src/pages/course-creation/ImageWidget.tsx
src/types/react-app-env.d.ts

https://github.com/corona-school/project-user/issues/1280
- Removed native-base from Unsplash related-components
- Replaced the direct call to the Unsplash API with our backend query
- Added some minor UI improvements to the Unsplash modal

Feat: Update Unsplash integration

---

src/App.tsx
src/components/ToastNotifications.tsx
src/components/notifications/MessageBox.tsx
src/components/notifications/NotificationAlert.tsx
src/context/GlobalModalsProvider.tsx
src/modals/LeavePageModal.tsx
src/widgets/InAppMessage.tsx

- Use the new toast component to show inApp notifications
- Fix the interaction of a notification should open a modal with the onClick event _(before it wasn't doing anything)_
- Moved all Modals from MessageBox to a GlobalModalsContext
https://github.com/user-attachments/assets/5d53b50f-6f74-4a9a-941d-e5689e2f5565

Feat: Notification improvements

---

src/Utility.ts
src/pages/registration/PersonalData.tsx

- Added utility to render emails as anchors in cooperation card

feat: Allow clickable emails on cooperation card

---

src/lang/de.json

Shortened text to make it more concise and save some space

text: German translations improvements

---

src/pages/pupil/matching/UpdateData.tsx
src/pages/student/matching/UpdateData.tsx

Introduce forced line wrap for federal state icon in student and pupil UpdateData.
Resolves corona-school/project-user#1351

fix missing line wrap for federal state icon

---

package.json
src/widgets/IconTagList.tsx

Widen CircleIcon from 8 to 10 to fix visual bug in onboarding survey
Resolves https://github.com/corona-school/project-user/issues/1352

Fix: minor-visual-bug

---

src/modals/RecommendModal.tsx
src/modals/RequireScreeningModal.tsx
src/pages/student/DashboardStudent.tsx

Resolves https://github.com/corona-school/project-user/issues/1354
Resolves https://github.com/corona-school/project-user/issues/1359
- Added tracking for Recommend section / Blocker Modal

Feat: Add matomo events

---

src/components/HeaderCard.tsx
src/hooks/useBreadcrumb.ts
src/lang/ar.json
src/lang/de.json
src/lang/en.json
src/lang/ru.json
src/lang/tr.json
src/lang/uk.json
src/pages/ChangeEmail.tsx
src/pages/ForPupils.tsx
src/pages/ForStudents.tsx
src/pages/Helpcenter.tsx
src/pages/InstallApp.tsx
src/pages/Progress.tsx
src/pages/ResetPassword.tsx
src/pages/SessionManager.tsx
src/pages/Settings.tsx
src/pages/notification/NotficationControlPanel.tsx
src/pages/pupil/ProfilePupil.tsx
src/pages/student/ProfileStudent.tsx

#687 
- Included missing `<Breadcrumb />` component in pages
- Added new translations

Feat: Add missing breadcrumbs

---

src/assets/icons/lernfair/ic_email.svg
src/assets/icons/lernfair/lf-timer.svg
src/components/PublicFooter.tsx
src/modals/RequireScreeningModal.tsx
src/modals/VerifyEmailModal.tsx
src/widgets/AppointmentCard.tsx

Resolves https://github.com/corona-school/project-user/issues/1360
- Included the PublicFooter _(Change Language + Legal Links)_ component on the Verify Email / Require Screening pages
- Removed native-base from those pages

Feat: Verify Email / Require Screening adjustments

---

src/components/notifications/MessageBox.tsx
src/hooks/useBreadcrumb.ts
src/lang/ar.json
src/lang/de.json
src/lang/en.json
src/lang/ru.json
src/lang/tr.json
src/lang/uk.json
src/pages/CreateCourse.tsx
src/widgets/AppointmentTile.tsx
src/widgets/InAppMessage.tsx

- Increase the size of the lecture title
- Add button to close inApp notification
- Fix breadcrumb on EditCourse page

Style: UI improvements

---

src/assets/icons/lernfair/lf-books.svg
src/pages/OnboardingTourList.tsx
src/pages/student/CourseBlocker.tsx
src/pages/student/DashboardStudent.tsx
src/widgets/AppointmentCard.tsx
src/widgets/CTACard.tsx

Resolves https://github.com/corona-school/project-user/issues/1364
- Removed "Meine Lernpartner:innen" section from the HuH dashboard
- Updated button variants to be less highlighted
- Truncate CTACard content to be max 4 lines
- Removed native-base from CTACard / Simplify it

Feat: Remove irrelevant content from huh dashboard

---

src/pages/student/MatchingStudent.tsx
src/pages/student/StudentGroup.tsx

Add "read more" button to MatchingStudent and StudentGroup
Resolves corona-school/project-user#1362

feat: Add "read more" button to MatchingStudent and StudentGroup

---

src/I18n.ts
src/Utility.ts
src/components/Calendar.tsx
src/components/appointment/AppointmentDetail.tsx
src/components/appointment/AppointmentsList/AppointmentCard.tsx
src/components/appointment/AppointmentsList/AppointmentDivider.tsx
src/lang/ar.json
src/lang/en.json
src/lang/ru.json
src/lang/tr.json
src/lang/uk.json
src/pages/Appointment.tsx
src/pages/subcourse/SubcourseData.tsx
src/widgets/AppointmentCard.tsx
src/widgets/AppointmentDate.tsx
src/widgets/AppointmentDay.tsx
src/widgets/AppointmentList.tsx
src/widgets/course/SubcourseCard.tsx

Resolves https://github.com/corona-school/project-user/issues/1361

Fix: Missing date translations

---

src/matomo.ts

https://github.com/corona-school/project-user/issues/1279

feat: Track referrers via Matomo

---

src/pages/student/SingleCourseStudent.tsx
src/pages/subcourse/SubcourseData.tsx

Resolves https://github.com/corona-school/project-user/issues/1370

fix: Ensure course exists before rendering SubcourseData component

---

src/pages/student/SingleCourseStudent.tsx

- Adjusted conditionals to show the page even if the student is not the instructor
- Put individual conditions for instructor-only sections

fix: SingleCourseStudent page when a non-instructor HuH visits it

---

src/pages/pupil/matching/Details.tsx
src/pages/student/matching/SchoolClasses.tsx
src/widgets/NextPrevButtons.tsx

Resolves https://github.com/corona-school/project-user/issues/1376
- Added loading state when creating a match to prevent double requests due to double clicks

Fix: Prevent multiple requests due to double clicks

---

src/widgets/screening/ScreenPupilCard.tsx
src/widgets/screening/ScreeningSuggestionCard.tsx

- Also show them for pupils not currently screened
- Allow sending multiple suggestions by resetting the UI after 5 seconds

fix: Screener Suggestions UI touchups

---

src/components/Toaster.tsx
src/lang/ar.json
src/lang/de.json
src/lang/en.json
src/lang/ru.json
src/lang/tr.json
src/lang/uk.json
src/pages/screening/Dashboard.tsx
src/pages/screening/components/UserCard.tsx
src/widgets/screening/EditGradeModal.tsx
src/widgets/screening/EditLanguagesModal.tsx
src/widgets/screening/EditSubjectsModal.tsx
src/widgets/screening/ScreenPupilCard.tsx
src/widgets/screening/ScreenStudentCard.tsx

As part of https://github.com/corona-school/project-user/issues/1337 and https://github.com/corona-school/project-user/issues/1379
- Added a new `UserCard` component to show as part of the user search results on the ScreeningDashboard 
- Removed native-base from some all of the ScreeningModals and also from the Screening Dashboard
- Refactored the Modals a bit so they contain their respective mutations and make them re-usable for pupils/students
No functionality changes are expected.

Refactor: Screening tool style improvements

---

src/components/appointment/AppointmentMetaDetails.tsx

Change alignment of lecture details to strictly vertically.
Resolves https://github.com/corona-school/project-user/issues/1373

fix: change alignment of qr-code

---

src/pages/course-creation/CourseClassification.tsx

Resolves https://github.com/corona-school/project-user/issues/1394

feat: Make tags optional when creating a course

---

src/pages/student/SingleCourseStudent.tsx
src/pages/subcourse/SubcourseData.tsx

- Allow screeners to see seats available in a course

feat: Allow screeners to see available course seats

---

src/pages/pupil/Group.tsx

fixes https://github.com/corona-school/project-user/issues/1405

fix: only show courses in either past or current section

---

src/components/VideoButton.tsx

FE Part of https://github.com/corona-school/project-user/issues/1395
- Updated the logic to get the Zoom meeting link when clicking the `Videochat Starten` button and use the new mutation

fix: Update logic to get zoom meeting link

---

package-lock.json
package.json
src/components/Button.tsx
src/components/Dropdown.tsx
src/lang/de.json
src/modals/VerifyEmailModal.tsx
src/pages/registration/PersonalData.tsx

- Adjusted styles based on feedback
- Fixed some typos
- Added option to logout on the verify modal (Added new Dropdown component)

Fix: Email confirmation feedback

---

src/components/DatePicker.tsx
src/context/AppointmentContext.tsx
src/pages/CreateAppointment.tsx
src/pages/create-appointment/AppointmentCreation.tsx
src/pages/create-appointment/AppointmentForm.tsx
src/pages/create-appointment/WeeklyAppointmentForm.tsx
src/widgets/CustomVideoInput.tsx

https://github.com/corona-school/project-user/issues/1412
- Removed native-base components from the Create Appointment form
- No major functionality changes expected

Refactor: Remove native base from create appointment

---

src/components/Combobox.tsx
src/modals/VerifyEmailModal.tsx
src/pages/screening/Dashboard.tsx
src/pages/screening/components/SchoolSearchInput.tsx
src/pages/screening/pupil/PersonalDetails.tsx

Resolves https://github.com/corona-school/project-user/issues/1414
- Allow screeners to enter custom schools
- Add icons indicating school finding state (Found on the API / Custom input)

Feat: Improve school search for screeners

---

src/context/AppointmentContext.tsx
src/pages/course-creation/CourseAppointments.tsx
src/pages/course-creation/CreateCourseAppointmentModal.tsx
src/pages/create-appointment/AppointmentCreation.tsx
src/pages/create-appointment/AppointmentForm.tsx

Resolves https://github.com/corona-school/project-user/issues/1420
- Added default time value on the create appointment form
- Removed native-base from CreateCourseAppointmentModal (fixes `Maximum call stack size exceeded`)

Fix: Appointment form adjustments

---

.github/workflows/deploy-storybook.yml
.github/workflows/main-barrier.yml
.github/workflows/verify-prod.yml

Resolves https://github.com/corona-school/project-user/issues/1426 
- Upgraded action packages

ci: Upgrade actions

---

src/pages/Login.tsx
src/pages/LoginWithIDP.tsx
src/pages/registration/UserType.tsx

- When users cancel the registration with SSO, we do a cleanup of the user session

Fix: Cleanup after canceling registration

---

src/components/Table.tsx
src/pages/screening/Dashboard.tsx
src/pages/screening/pupil/PupilDetail.tsx
src/pages/screening/student/StudentDetail.tsx
src/types/index.ts
src/widgets/screening/ScreeningSuggestionCard.tsx
src/widgets/screening/SuggestionsHistory.tsx

Resolves https://github.com/corona-school/project-user/issues/1425
- Added a new table component
- Show the Suggestions History on the screening tool

Feat: Add suggestions history

---

src/components/BottomNavigationBar.tsx
src/components/referral/rewards.tsx
src/hooks/useBreadcrumb.ts
src/pages/Referrals.tsx
src/pages/Settings.tsx
src/pages/create-appointment/AppointmentCreation.tsx

- Hide referral item on the mobile bottom bar
- Adjust font-weight on referrals page
- Add matomo page view event
- Add breadcrumb on referrals page

Fix: UI Feedback

---

src/pages/screening/pupil/PupilDetail.tsx
src/pages/screening/student/StudentDetail.tsx

- Show pupil/student active state

feat: Add active state in screening tool

---

src/components/referral/socialOptions.tsx
src/pages/Referrals.tsx
src/pages/student/Certificates.tsx

Resolves https://github.com/corona-school/project-user/issues/1418
- Added Matomo events for referrals page & certificate page buttons

Feat: Add tracking events

---

src/Utility.ts
src/widgets/screening/EditSubjectsModal.tsx

- Added default min / max grade range on the EditSubjectsModal

fix: Add default min max grade range on the editSubjectsModal

---

src/pages/SingleMatch.tsx
src/widgets/matching/MatchPupilCard.stories.tsx
src/widgets/matching/MatchStudentCard.stories.tsx

- remove dissolveReason from SingleMatch query as it was removed and isn't needed here
- remove dissolveReasonEnum from Storyboard files

Fix: remove `dissolveReason[Enum]`

---

public/index.html
src/components/WithNavigation.tsx

Resolves https://github.com/corona-school/project-user/issues/1437
- Added open graph tags

feat: add open graph tags

---

src/pages/student/Certificates.tsx

Resolves https://github.com/corona-school/project-user/issues/1442

fix: Add loading state to the Download certificate button

---

src/components/ZoomMeeting.tsx

Resolves https://github.com/corona-school/project-user/issues/1460

Hotfix: Include ZoomMeetingPassword if any

---

src/pages/screening/pupil/PersonalDetails.tsx
src/pages/screening/pupil/PupilDetail.tsx
src/pages/screening/pupil/ScreenPupil.tsx
src/pages/screening/pupil/useUpdatePupil.ts

Resolves https://github.com/corona-school/project-user/issues/1448
- Save pupil profile changes after saving screening information
- Move update pupil logic to a separate function/hook

feat: Save pupil profile after saving screening

---

src/pages/Chat.tsx

Partially resolves https://github.com/corona-school/project-user/issues/1450
- Added support for a conversationId query param

feat: Allow preselect a chat

---

src/components/notifications/NotificationAlert.tsx
src/pages/Chat.tsx

- Notifications popover is not shown on chat view
- Automatically select chat if a `conversationId` parameter is present

Feat: Notifications improvements

---

src/pages/screening/SingleCourseScreener.tsx

- Changed the variables used to allow/deny courses to use the correct ones

Hotfix: Use courseId instead of subcourseId

---

src/modals/RequireScreeningModal.tsx
src/pages/screening/Dashboard.tsx
src/pages/screening/components/UserCard.tsx
src/pages/screening/student/ScreenStudent.tsx
src/types/index.ts
src/widgets/screening/StudentScreeningCard.tsx

Frontend part of https://github.com/corona-school/project-user/issues/1464
- Replaced usage of `success` with `status` on the student screenings objects

feat: Replace usage of success field with status field

---

src/hooks/useJoinCourseAsMentor.tsx
src/pages/student/SingleCourseStudent.tsx
src/pages/student/onboarding/GroupOnboarding.tsx
src/widgets/OnboardingCard.tsx

- Resolves https://github.com/corona-school/project-user/issues/1481
- Added a hook to join the Hausaufgabenhilfe, it's now used in the detail page (for instructors) and on the courses blocker (for non-instructors)
- Updated the Courses Blocker page to include a Hausaufgabenhilfe banner, to allow users to join the course even if they're not instructors

Feat: Allow non instructors to join hah course

---

src/modals/RequireScreeningModal.tsx

Update screening status checks and improve appointment handling in RequireScreeningModal

fix: Logic to display Calendly widget and screening statuses

---

src/pages/pupil/ProfilePupil.tsx
src/pages/student/ProfileStudent.tsx

- Added a link to the HuH and SuS profile page to link to that edit-email page
Closes https://github.com/corona-school/project-user/issues/1407

link to email update page from HuH and SuS profile page

---

src/pages/registration/RegistrationStep.tsx
src/pages/registration/UserLanguages.tsx

- Padding adjustment on the languages step
- Allow to continue to the next step when pressing the enter key.

Feat: Registration funnel feedback

---

src/components/AddToCalendarDropdown.tsx
src/pages/registration/AcceptanceCheck.tsx
src/pages/registration/AcceptanceCheckFailed.tsx
src/pages/registration/AuthenticationInfo.tsx
src/pages/registration/BookAppointment.tsx
src/pages/registration/ConfirmEmail.tsx
src/pages/registration/DataPrivacy.tsx
src/pages/registration/EmailOwner.tsx
src/pages/registration/NotificationPreferences.tsx
src/pages/registration/OurRules.tsx
src/pages/registration/PupilGrade.tsx
src/pages/registration/SchoolSearch.tsx
src/pages/registration/SchoolType.tsx
src/pages/registration/ScreeningAppointmentDetails.tsx
src/pages/registration/UserAge.tsx
src/pages/registration/UserLanguages.tsx
src/pages/registration/UserName.tsx
src/pages/registration/UserTypeSelector.tsx
src/pages/registration/ZipCode.tsx

Added tracking events / page titles to the new registration steps

Feat: Add Matomo events to the registration steps

---

src/lang/de.json

updated texts in the new funnel - small typos and simpler language

Update text de funnel
