- src/pages/Login.tsx
@Jonasdoubleyou this solves the issue for now but I don't really understand why the login mutation threw an error in the first place. Shouldn't it just have been written into the error object of `loginResult` even with the default error policy?
> Set error policy of login mutation to 'all' (project-user#526)

- src/pages/pupil/Profile.tsx
- src/pages/student/ProfileStudent.tsx
This means that probably always the user is redirected to the settings page. It is a little unintuitive though that the settings have a separate route given the burger menu button. This is addressed in corona-school/project-user#539.
> On back redirect to previous page on profile pages (project-user#521)

- src/helper/notification-helper.ts
notifications that are older than two days will now show the date. (`dd-mm-yyyy`)
> Fix wrong notifications date text

- src/pages/pupil/ProfilePupil.tsx
- src/pages/student/ProfileStudent.tsx
Currently, the pupil/student profile completion value can only reach 100% if they've created a matching request.
This might confuse the user as the matching request is neither part of the profile page nor do we provide more information.
This PR takes the most straightforward solution by removing this vector from the calculation. Nevertheless, we could also update the profile view to add a link to the matching flow.
closes:  https://github.com/corona-school/project-user/issues/523
> remove subjectsFormatted from pupil profile completeness

- src/lang/lernfair/de.ts
- src/pages/pupil/Dashboard.tsx
- src/pages/pupil/MatchingOnboarding.tsx
Wording taken over from https://www.notion.so/lern-fair/Warteschlange-schlie-en-5fdc2267874c4304a003a80f184f9b98
For users that already have a match or open match request, it does not make sense to show the alert on the Dashboard. 
I think it is better to just hide the button on the dashboard if Match Requests are disabled. 
Also if we know a specific reason why they cannot request another match (i.e. "you already have a match request" / "you already have a match") then that is shown instead of the generic reason "currently no new match requests" as that is not that relevant for the user (and especially for users that already have a match or match request that could be missleading)
> Remove Match Request disabled alert from Dashboard, adapt wording

- src/hooks/useApollo.tsx
- src/pages/CoursePage.tsx
- src/pages/MatchPage.tsx
- src/types/lernfair/User.ts
With the changes made in https://github.com/corona-school/backend/pull/578, we can now drop additional requests when navigating between tabs and can rely on the user roles present in the session
> Use wannabe roles to show onboarding pages

- src/components/FilePicker.tsx
- src/modals/SendParticipantsMessageModal.tsx
Small Frontend changes for a more [resilient Fileupload](https://github.com/corona-school/project-user/issues/731):
- max filesize 5mb (capped by multer in backend)
- extracted uploadFiles function for better reusability of the filePicker component
I will focus on the Backend part of https://github.com/corona-school/project-user/issues/731 next
> Refactor fileUpload component

- src/IssueReporter.tsx
This PR splits the error / component stack into different variables, so that we can log them separately.
> fix: split error / component stack in issue reporter

- src/lang/helpcenter/de.ts
Closes https://github.com/corona-school/project-user/issues/757
Text was replaced with "Klicke dich hier durch häufig gestellte Fragen oder kontaktiere unser Team.", because the "Hilfestellungen" tab seems to have been previously removed.
> 757 replace help text

- src/lang/helpcenter/de.ts
- src/pages/Helpcenter.tsx
Fixes little mistake made in solution to https://github.com/corona-school/project-user/issues/757
Renders different support tab texts for students and pupils, because they have different tabs each:
subtitle: {
pupil: 'Klicke dich hier durch häufig gestellte Fragen oder kontaktiere unser Team.',
student: 'Klicke dich hier durch unsere pädagogischen & technischen Hilfestellungen, unsere häufigen Fragen oder kontaktiere unser Team.',
}
> show different support tab text for pupils and students

- src/pages/create-appointment/AppointmentForm.tsx
- src/widgets/Select.tsx
We had the problem, that only a single character is accepted on controlled input.
So it seems that the problem occures when a select element is present with an input on the same page.
refers to https://github.com/corona-school/project-user/issues/853
> fix: input problem on appointment creation on safari

- .storybook/preview.tsx
- README.md
- src/NavigatorLazy.tsx
- src/User.tsx
- src/components/BottomNavigationBar.tsx
- src/components/InfoCard.stories.mdx
- src/components/InfoCard.tsx
- src/components/LanguageTag.stories.mdx
- src/components/LanguageTag.tsx
- src/components/SideBarMenu.tsx
- src/components/SubjectTag.stories.mdx
- src/components/SubjectTag.tsx
- src/components/Tag.tsx
- src/hooks/useApollo.tsx
- src/lang/de.ts
- src/lang/screening/de.ts
- src/lang/shared/de.ts
- src/modals/ConfirmModal.stories.mdx
- src/modals/ConfirmModal.tsx
- src/pages/Settings.tsx
- src/pages/screening/Dashboard.tsx
- src/types/index.ts
- src/widgets/matching/MatchStudentCard.stories.mdx
- src/widgets/matching/MatchStudentCard.tsx
- src/widgets/screening/PupilScreeningCard.stories.mdx
- src/widgets/screening/PupilScreeningCard.tsx
- src/widgets/screening/ScreenPupilCard.stories.mdx
- src/widgets/screening/ScreenPupilCard.tsx
Adds the possibility for Screeners to Log in to the User App, see pupils with disputed screenings (another screener did the screening but did not decide yet) as well as search for pupils (for example when a pupil booked a screening appointment). Screeners can then leave a screening comment, mark the screening as success or rejection, or deactivate the pupil's account.
----
Additionally fixes and documents stateful Storybooks.
----
To test the actual Screening, request a Screening for i.e. "Max Musterschüler":
```
mutation { 
pupilCreateScreening(pupilId: 1)
}
```
When done, login with auth token "authtokenSC1" or "test+dev+sc1@lern-fair.de" and password "testtest" (changed it on staging, after the next deployment it'll be "test" again). Then search for pupils, with i.e. …
> feat: Pupil Screening

- src/index.tsx
Stopping session replay to investigate performance issues. Will be reactivated or removed when Support finally give an answer why it's not working for us.
> stop session replay for now

- src/IssueReporter.tsx
Apparently Zoom sometimes throws around error messages, and then the IssueReporter does more harm than good. We now have Datadog RUM anyways.
> fix: Remove Issue Reporter for unhandled errors 

- src/helper/notification-helper.ts
- src/hooks/useNotificationPreferences.ts
refers to: https://github.com/corona-school/backend/pull/809
> fix: notification preferences

- src/pages/Registration.tsx
On mobile we make the header much smaller, giving more space for actual content
> fix: Make Registration more usable on mobile

- package-lock.json
- package.json
This PR will use a newer version of the Datadog browser SDK with the following changes
* update to v4.49.0
* use sessionStorage instead of local map
Here are the changes:
* [Code changes](https://github.com/corona-school/browser-sdk/pull/11)
* [New packes](https://github.com/corona-school/browser-sdk/pull/12)
> feature: upgrade browser sdk and use session storage instead of map

- src/pages/Chat.tsx
So what, let's include the Chat in Session Replay. Overhead should be small, but getting the layout right is harder than expected
> fix: Revert Chat Layout changes

- src/components/LanguageTag.tsx
- src/components/SubjectTag.tsx
- src/widgets/matching/MatchStudentCard.tsx
- src/widgets/screening/ScreenPupilCard.tsx
Resolves https://github.com/corona-school/project-user/issues/926
Not sure if this is exactly what you want, but now you can deactivate an account without creating a new screening:
> feat(screening-dashboard): deactivate account without open screening

- src/hooks/useApollo.tsx
- src/types/lernfair/User.ts
- src/widgets/screening/ScreenPupilCard.tsx
Add user impersonation button if screener has TRUSTED_SCREENER role
Frontend part of https://github.com/corona-school/project-user/issues/928
I had to implement a workaround for the "open in new tab" functionality as it was blocked by the browser's popup blocker (apparently you can only call it in synchronous onClick event handlers..)
> Add user impersonation button if screener has TRUSTED_SCREENER role

- src/lang/matching/de.ts
- src/modals/DissolveMatchModal.tsx
- src/pages/SingleMatch.tsx
- src/pages/pupil/Dashboard.tsx
- src/pages/student/DashboardStudent.tsx
Resolves https://github.com/corona-school/project-user/issues/948
Further Comments/Questions:
1. the DissolvedMatchModal is also referenced but not used in the Student- and Pupil Dashboard. Should I remove them there or will they be used in the future?
2. The currentIndex is not set inside the Modal:
so that part is unreachable:
and could be removed.
> feat(dissolve-match-modal): showing warning modal for first 14 days

- src/pages/student/SingleCourseStudent.tsx
Simply close the modal before the user can click again
resolves https://github.com/corona-school/project-user/issues/932
> fix: Course can be cancelled twice

- src/widgets/screening/ScreenPupilCard.tsx
A trusted screener might want to log in with the user's account regardless of it's current state.
Also hide it for deactivated accounts, as login won't work then anyways.
> fix: Always show user impersonation button

- src/components/VideoButton.tsx
Instead of loading the override link in every appointment-related query (which causes problems for non-participants), only load the link when the "join meeting" button is pressed.
> Override meeting link (2nd attempt)

- src/components/ProgressSpinnerModal.tsx
- src/lang/de.json
- src/widgets/certificates/MatchCertificateCard.tsx
- Show progress via Modal so that users do not "wait for nothing"
- Download via Link click instead of `window.open`, as that is unreliable in async contexts (browsers block "popups")
> feat: Improve Certificate download

- src/context/ChatContext.tsx
The number of unread messages is also incorrect, if the unread message is a system message.
- Closes https://github.com/corona-school/project-user/issues/1092
**ConversationListItem**
```
<div t:if="{{ isUnread and lastMessage.type == 'UserMessage' }}" class="unread-dot">
<span t:if="{{ unreadMessageCount > 999 }}">
999+
</span>
<span t:else-if="{{ unreadMessageCount > 0 }}">
{{ unreadMessageCount }}
</span>
</div>
```
> fix: disable notifications for system messages

- src/lang/de.json
- src/pages/pupil/Dashboard.tsx
- Remove the "no recommendations" alert if there are no recommendations
- Also hide the course recommendations if the pupil is not a participant and thus cannot actually join courses
> feat: Remove "no recommendations" recommendation

- src/NavigatorLazy.tsx
- src/User.tsx
As we plan to revoke permissions from some pupils, we might have users that have bookmarked a link or got emails to join a certain course or so. We now properly redirect them to the Dashboard, where they are asked to join a screening.
> feat: Prevent users from accessing restricted pages

- src/components/GradeSelector.tsx
- src/components/LanguageTag.tsx
- src/pages/registration/SchoolClass.tsx
- src/pages/screening/Dashboard.tsx
- src/types/index.ts
- src/widgets/screening/EditGradeModal.tsx
- src/widgets/screening/EditLanguagesModal.tsx
- src/widgets/screening/ScreenPupilCard.tsx
- Allow Screeners to edit grade and languages of pupils
- Allow Screeners to request and revoke match requests on behalf of pupils
- When a screener creates a screening, the user is not notified (this happens when the pupil booked an appointment anyways, i.e. during the initial screening)
https://github.com/corona-school/project-user/issues/1142
https://github.com/corona-school/project-user/issues/1141
https://github.com/corona-school/project-user/issues/740
> feat: Screening Tool Improvements for initial pupil screening

- package-lock.json
- package.json
Apparently gitpkg changed something and loading the package will redirect to a different domain. For some reason then on some clients (even with same npm version) the hash is different - as if some clients do not follow the redirect but
hash something else. Very weird though.
> ci: Remove redirect from dependency

- src/components/notifications/MessageBox.tsx
When clicking on a Notification, if it navigates to the special /achievement/{achievementId} link, open the achievement modal instead
picked from #420
> feat: Achievement modal for notification

- src/components/achievements/progressIndicators/IndicatorBarWithSteps.tsx
This PR is changing the progress bar appearance from this
To this:
> fix: progress bar should be half filled if we are on the way to the next step

- src/components/achievements/achievementCard/AchievementCard.tsx
- src/widgets/AchievementProgress.tsx
This will remove the progress bar from future achievements like this
> feature: hide progres bar for future/completed achievements

- src/lang/de.json
- src/modals/ReportMatchModal.tsx
- src/pages/SingleMatch.tsx
https://github.com/corona-school/project-user/issues/1132
https://github.com/corona-school/backend/pull/1042
- Added a new `ReportMatchModal` that contains the form and the API call to submit a match report.
- Included the new component on the `SingleMatch` page.
- Problem description field should be required for students
- Report Problem button is gone after 30 days _(it uses the same logic as the Chat button)_
Modal looks like this _(Text changes for pupils)_:
> feat: Report match modal

- src/pages/Login.tsx
Enforce entering of the password in case it is required, in order to avoid error 400.
Closes https://github.com/corona-school/project-user/issues/1152.
> Fix: Enforce password

- src/Theme.ts
- src/components/Tabs.tsx
- src/modals/NotificationPreferencesModal.tsx
- src/modals/RequireScreeningModal.tsx
- src/widgets/RequireScreeningSettingsDropdown.tsx
https://github.com/corona-school/project-user/issues/1159
- Added a new `RequireScreeningSettingsDropwon` that will appear on the screening blocker. This component allows the user to deactivate their account, or change their notifications preferences _(via a new `NotificationsPreferencesModal` which just re-uses the existing component but in a modal)_.
- Added links to Datenschutz and Impressum, similar to how we do it in the login page
- Slightly updated how a "full" modal look like, so it at least have some space on the sides which looks a bit better. I checked and this modal size was only being used on the screeners section, and it's still looking good with the new changes.
Here is how it looks like:
https://github.com/corona-school/user-app/assets/161815068/22bd1564-7727-433b-810d-24ba …
> Feat: Add settings on the screening blocker

- src/User.tsx
- src/components/Tabs.tsx
- src/helper/screening-helper.ts
- src/helper/string-helper.ts
- src/lang/de.json
- src/modals/RequireScreeningModal.tsx
- src/pages/student/onboarding/GroupOnboarding.tsx
- src/pages/student/onboarding/MatchOnboarding.tsx
- src/types/lernfair/User.ts
- src/widgets/ImportantInformation.tsx
https://github.com/corona-school/project-user/issues/1154
- Updated existing mandatory screening modal for pupils to also work for students
- Included some very minor refactor about the creation of screening links
- Add a default selected tab value in the `Tabs` component
Here is how it looks like:
During my tests I only noticed a weird behavior and is that when approving a student for tutoring, their sessions isn't being updated, so they cannot continue to the app until they re-login.
I'll follow up with a backend PR to update [here](https://github.com/corona-school/backend/blob/1c73699ee9ad757187e7f90b29ffe4e579a71747/common/student/screening.ts#L64) the user session when they get approved for tutoring. Similar to how we are doing it …
> feat: Mandatory screening for students

- src/pages/screening/Dashboard.tsx
- src/types/index.ts
- src/widgets/screening/ScreenPupilCard.tsx
https://github.com/corona-school/project-user/issues/1173
- Add a tooltip indicating why the "Screening anlegen" button is disabled
https://github.com/corona-school/user-app/assets/161815068/3a87f01b-f817-45b6-816e-f14b3c13a05e
- Follow up backend PR that grants screeners access to the verifiedAt property
> feat: Show reason for disabling the create screening button

- src/NavigatorLazy.tsx
- src/User.tsx
https://github.com/corona-school/project-user/issues/1167
Set the existing `isRetainPath` prop on the `RequireAuth` component to `true`. I couldn't think of a scenario where this isn't the desired behavior. If there is any, we could rather exclude them individually.
https://github.com/corona-school/user-app/assets/161815068/370d5297-3f28-4178-9f4a-bdf4ddecb08a
> fix: Add default isRetainPath to all routes

- src/pages/SingleMatch.tsx
- src/widgets/AppointmentList.tsx
- src/widgets/MatchAppointments.tsx
https://github.com/corona-school/project-user/issues/1177
- Added pagination to the match appointments list, similar to how the general appointments page works
- Fixed the loading behavior of the appointments component to show an spinner on the `Vergangene Termine laden` button when appointments are being fetched
https://github.com/corona-school/user-app/assets/161815068/b52c69d7-5d8a-4ea0-84d8-5f5fe17772ce
[Backend PR](https://github.com/corona-school/backend/pull/1061)
> Feature: Lazy load match appointments

- src/pages/Appointments.tsx
- src/pages/SingleMatch.tsx
- src/widgets/AppointmentList.tsx
- Hide the load past buttons when there are no more appointments to fetch (depends on [this backend PR](https://github.com/corona-school/backend/pull/1064))
- Updated the AppointmentsList to load more appointments before reaching the end of the list _(When the last item is shown)_
> Fix: Load past appointments button behavior

- src/hooks/useApollo.tsx
Make the Apollo Plugin work with the cache
> fix: Apollo Plugin + Cache

- src/components/BackButton.tsx
- src/components/Tabs.tsx
- src/components/notifications/preferences/PreferenceItem.tsx
- src/components/notifications/preferences/Preferences.tsx
- src/components/notifications/preferences/ToggleAll.tsx
- src/hooks/useNotificationPreferences.ts
- src/lang/de.json
- src/pages/notification/NotficationControlPanel.tsx
- src/routing/NavigatorLazy.tsx
https://github.com/corona-school/project-user/issues/1149
- Added two sub-routes `notifications/system` and `notifications/newsletter` that control the tabs
- Added a `?unsubscribe` on the `notifications/newsletter` route for 1-click-opt-out in emails
- Replaced the switches with checkboxes as suggested
- Added toast messages when preferences are updated
> Feature: Notification preferences opt out url + minor UI improvements

- .eslintrc
- README.md
- serve.js
- src/App.tsx
- src/config.ts
- src/lib/WebPush.ts
- src/pages/WebPush.tsx
- src/routing/NavigatorLazy.tsx
- src/service-worker-proxy.ts
- src/service-worker.ts
- src/types/react-app-env.d.ts
- tsconfig.json
If the runtime config `RUNTIME_SERVICE_WORKER_ACTIVE` is turned on, registers a service worker that
- Caches static resources of the App (with a bit of config the app would start offline)
- Receives Push Notifications, and shows a generic notification
- Handles a click on the notification and opens the User App
Also adds a hidden page `/push` where one can turn on push notifications - might come in handy during a "Beta" phase were we ask users to test it (very rudimentary UI). 
https://github.com/corona-school/project-user/issues/606
> feat: Service Worker + Web Push

- src/pages/student/SingleCourseStudent.tsx
Updated the canPromote field to read `.allowed` after changes made in: https://github.com/corona-school/backend/pull/1091
> fix: Update canPromote field to use allowed

- src/config.ts
- src/pages/Settings.tsx
- src/types/react-app-env.d.ts
To test on iOS, one needs to open the push settings in the installed PWA, which can only be done if there is a button navigating to it (as there is no address bar)
> feat: Link Push config from settings

- src/components/BackButton.tsx
- src/pages/ForPupils.tsx
- src/pages/ForStudents.tsx
Back button is displayed only on mobile on the `Wissen` pages
> feat: Allow BackButton only on mobile on the knowledgeCenter page

- src/web/scss/index.scss
Interestingly if the 'Montserrat' font fails to load, instead of falling back to other fonts specified (i.e. through the Zoom CSS styles (WTF)), due to the `!important` annotation it will not take any fallback, but render with a "not found font". By adding a fallback font (i.e. `sans-serif`) to the important rule itself, if the font fails to load it will still look relatively okay.
> fix: Font fallback

- src/pages/create-appointment/AppointmentCreation.tsx
- src/pages/create-appointment/AppointmentForm.tsx
- src/widgets/InputSuffix.tsx
InputSuffix.tsx: set appointmentsCount as optional input parameter. Name of input field is named "Lektion" if no appointmentsCount is provided and "Lektion #{appoinmentsCount}" otherwise.
AppoitmentForm.tsx: delete input prop appointmentsCount from <Input Suffix />. AppointmentForm.tsx is only used once and appointmentsCount is also no longer used in AppointmentsForm, so I deleted the input prop appointmentsCount.
AppointmentCreation.tsx: deleted input prop appointmentsCount from <AppointmentForm />.
Resolves corona-school/project-user#1252
> fix: delete count in AppointmentForm

- src/pages/pupil/Dashboard.tsx
- src/widgets/CTACard.tsx
CTACard.tsx: introduced a flag buttonIsBanner. If set, the attribute flexBasis of the cta-card__item--button is set to 100%. So a line-break is forced for the banner.
Dashboard.tsx: The CTACard is called with the new prop buttonIsBanner = true
Resolves corona-school/project-user#1240
> fix: The banner is now placed under the text of the CTA card

- src/App.tsx
- src/components/notifications/preferences/SystemNotifications.tsx
- src/context/WebPushProvider.tsx
- src/hooks/useLogout.ts
- src/lib/WebPush.ts
- src/log.ts
- src/modals/DeactivateAccountModal.tsx
- src/pages/Settings.tsx
- src/widgets/RequireScreeningSettingsDropdown.tsx
https://github.com/corona-school/project-user/issues/1264
- Split the unsubscribe process into two, giving "priority" to the local unsubscription
- Store the user decision of the Switch (on/off) on local storage _(Not sure why I didn't do this in the first place 🤦 )_
- Unsubscribe when a user logs out
- Subscribe if user preferences require us to do so and if webPush state is `not-subscribed`
> Fix: Push subscribe and unsubscribe behavior when logout/login

- package-lock.json
- package.json
- public/index.html
- src/Theme.ts
- src/components/ResizableTextArea.tsx
- src/components/ZoomMeeting.tsx
- src/components/notifications/NotificationAlert.tsx
- src/index.tsx
- src/pages/match/MatchPartner.tsx
- src/widgets/CustomVideoInput.tsx
- src/widgets/InputSuffix.tsx
https://github.com/corona-school/project-user/issues/1239
- Finished React 18 Upgrade _(Required for new Zoom version)_
- React 18 broke Native-base, so I upgraded it as well to a version that fixed the issues
- Upgraded Zoom to the latest version. The only relevant things I noticed _(So far)_ are:
- Package now lives under `@zoom/meetingsdk`
- A few methods deprecated that don't seem to be needed anymore
- No need to load CSS dependencies in our index.html
> Feat: Update Zoom SDK

- README.md
- docs/upgrade-dd-browser-sdk-fork.md
- package-lock.json
- package.json
Upgrading our DataDog browser-sdk fork to v5.22
> chore: upgrade dd browser sdk to v5.22

- package-lock.json
https://github.com/EqualMa/gitpkg/issues/58
Dependencies should be changed from gitpkg.now.sh to gitpkg.vercel.app
https://github.com/corona-school/browser-sdk/compare/b8161bbdc38b2b4c222472a7f5ec552da8efd52c..2abc2348641bd0882ef4cfda0ee8015ed5bb3d60
> fix: gitpkg.now.sh was deprecated

- src/pages/ChangeEmail.tsx
- src/pages/ForStudents.tsx
- src/pages/Helpcenter.tsx
- src/pages/ResetPassword.tsx
- src/pages/Settings.tsx
- src/pages/notification/NotficationControlPanel.tsx
- src/pages/pupil/ProfilePupil.tsx
- src/pages/student/ProfileStudent.tsx
- src/routing/NavigatorLazy.tsx
Update head navigation of following pages:
/profile, /notifications/system, /help-area, /new-email, /new-password, /imprint, /privacy
...as follows:
Desktop: there is the sidebar navigation on the left, in the header there is the LanguageSwitchButton, the notification banner and the hamburger
Tablet: see Desktop, besides hamburger on left side
Mobile: there is no sidebar navigation, in the header there is only the BackArrow button
Resolves corona-school/project-user#1248
> Remove additional icons from settings sub pages head navigation

- src/pages/CreateCourse.tsx
- The finishCourseCreation function now accepts two parameters: errors and courseId.
- Instead of navigating back to the group page after the user edits their course, they will now automatically return to the details page of that specific course.
- The courseId value is passed to the finishCourseCreation function at the necessary points within the code.
https://github.com/corona-school/project-user/issues/1047
> feat: Navigate back to course detail page after edit

- src/components/Tag.tsx
- src/widgets/SubjectList.tsx
- Enhanced the styling of "Tag.tsx" and "SubjectList.tsx" components to prevent the subject list from overflowing on the match request card when viewed on smaller screens or when many subjects are selected.
https://github.com/corona-school/project-user/issues/1038
> fix: Make Match Request Card Responsive

- src/lang/ar.json
- src/lang/de.json
- src/lang/en.json
- src/lang/ru.json
- src/lang/tr.json
- src/lang/uk.json
- src/pages/ForStudents.tsx
- src/routing/NavigatorLazy.tsx
- Added a new tab to the student knowledge center called "Free consultation / Kostenlose Beratung"
- The tab renders the mentoring-beratung iFrame: https://www.lern-fair.de/iframe/mentoring-beratung
- Added translations for all supported languages
https://github.com/corona-school/project-user/issues/1293
> feat: Add iFrame "Mentoring" to Wissens-Center for HuH

- src/components/notifications/MessageBox.tsx
- Added the Pressable component inside the Tooltip component wrapping the tooltip-text to ensure the tooltip body text is also clickable
https://github.com/corona-school/project-user/issues/1284
> fix: Notifications don't execute click actions on body text

- .babelrc.js
- package.json
- src/hooks/useApollo.tsx
- src/widgets/screening/ScreenPupilCard.tsx
https://github.com/corona-school/project-user/issues/1273
- Added the recommended `BabelOptimizerPlugin` as suggested in the [documentation](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size)
With this change, I noticed that the big map in `gql.ts` is not included in the build anymore but instead uses the generated types.
_Note: After adding our new components the final build size increased _(as expected)_, this will unfortunately be like this until we remove native-base + friends which right now is around 22% of the build._
> Ci: Add gql codegen plugin

- src/routing/NavigatorLazy.tsx
On desktop, the legal notice and privacy policy pages load the sidebar menu through the `WithNaviation` component, which leads to an error if the user is not logged in (the pages are accessible through links on the login page)
Closes https://github.com/corona-school/project-user/issues/1306
> Fix privacy policy & legal notice if user is not logged in

- src/service-worker-proxy.ts
... by logging it instead of having an unhandled promise rejection. If the user's browser does not want our service worker, so be it.
> fix: Handle service worker registration failure

- src/hooks/useApollo.tsx
- src/pages/Appointments.tsx
- src/pages/SingleMatch.tsx
Unfortunately pagination in GraphQL is terribly broken, and we update the query result of an existing query with fetchMore(...) passing in other variables, without changing the original variables of the query. Thus this messes up the cache.
Unfortunately for some reason cachePolicy: "no-cache" does not work and the cache is still taken :/ Thus adding a hack to skip the cache, by adding NO_CACHE in the query name
https://github.com/corona-school/project-user/issues/1310
> fix: Skip cache for appointment queries

- src/components/Label.tsx
- src/components/Modal.tsx
- src/components/SideBarMenu.tsx
- src/components/SwitchLanguageButton.tsx
- src/components/Toaster.tsx
- src/modals/AppFeedbackModal.tsx
- src/modals/SwitchLanguageModal.tsx
- src/pages/Settings.tsx
https://github.com/corona-school/project-user/issues/1323
Partially: https://github.com/corona-school/project-user/issues/1305
- Updated the SwitchLanguageModal & AppFeedbackModal to use the new components
- Fixed toast behavior when a modal is open _(for the `AppFeedbackModal`)_ by adding a portal for the toaster to render it on the body
> Feat: UI facelift SwitchLanguageModal & AppFeedbackModal

- src/components/Modal.tsx
- src/modals/AddPupilModal.tsx
- src/modals/AppFeedbackModal.tsx
- src/modals/CancelSubCourseModal.tsx
- src/modals/CourseConfirmationModal.tsx
- src/modals/IncreaseMaxParticipantsModal.tsx
- src/modals/RemoveParticipantFromCourseModal.tsx
- tailwind.config.js
Adjust modal footer layouts to display buttons correctly on mobile/desktop
- Mobile default: 50/50
- Mobile destructive: 50/50 + reverse
- Desktop default: Align-end / width fit
- Desktop destructive: Align-end / width fit + reverse
> Style: Modal footer layout

- src/pages/ForPupils.tsx
- src/pages/ForStudents.tsx
- src/pages/pupil/SingleCoursePupil.tsx
- src/pages/student/SingleCourseStudent.tsx
- src/pages/subcourse/SubcourseData.tsx
- Removed unneeded top padding in knowledge-center pages
- Fixed white-space on course descriptions so they are easier to read
- Fixed double scroll on the course detail page
> Fix: Minor styling adjustments

- src/components/notifications/preferences/SystemNotifications.tsx
- src/modals/InformationModal.tsx
- src/pages/Login.tsx
https://github.com/corona-school/project-user/issues/1305
- Removed native-base from `InformationModal` to re-use it in other places
- Replaced the remaining overflowing modals with the new `InformationModal` that doesn't cause overflow with the title and the close button
> Fix: Overflowing modals

- src/components/SettingsButton.tsx
- src/components/SwitchLanguageButton.tsx
- src/components/notifications/NotificationAlert.tsx
- src/pages/Welcome.tsx
- src/web/index.css
- tailwind.config.js
Addressing some of the feedback we got after the recent release:
- Fixed the primary-light color to match the landing page one
- Added hover styles to the top navigation items (also included a small animation to the bell icon when hover)
https://github.com/user-attachments/assets/fc75d84e-90eb-48f1-9af5-6fc02290e5e7
> Style: Navbar improvements

- src/hooks/useConcreteNotification.ts
- src/modals/AchievementMessageModal.tsx
- Skip achievementById query if no id is given
- Include `navigateTo` when receiving new inApp notification to allow onClick event on floating component
> Fix: Minor achievement and notification issues

- src/pages/pupil/Dashboard.tsx
- src/pages/pupil/ProfilePupil.tsx
- src/pages/student/DashboardStudent.tsx
- src/pages/student/ProfileStudent.tsx
Partially tackles https://github.com/corona-school/project-user/issues/1302
- Added back the greeting message but this time only on the Dashboard page
> Feat: Add back greeting on dashboard page

- src/hooks/useApollo.tsx
https://github.com/corona-school/project-user/issues/1353
- Move watchers to a separate map to avoid losing them when the cache entry is removed. With this, features like `refetchQueries` on `useMutations` work again _(Which fixes the reported issue)_
> fix: Cache watchers behavior

- src/components/Breadcrumb.tsx
- src/pages/Appointment.tsx
- Fixed breadcrumb ellipsis on mobile
- Fixed Appointment page breadcrumb by adding relation item _(Course / Match)_
> Fix: Breadcrumb styles / Ellipsis on mobile

- src/widgets/SubjectSelector.tsx
For SuS same selectable subjects shall be shown as for HuH.
Updated SubjectSelector.tsx with more specific subject arrays SUBJECTS_MAIN, SUBJECTS_MINOR and SUBJECTS_RARE (which are used for HuH).
Resolves corona-school/project-user#1350
> SuS: update selectable subjects

- package-lock.json
- package.json
- src/components/CenterLoadingSpinner.tsx
- src/modals/RequireScreeningModal.tsx
Resolves https://github.com/corona-school/project-user/issues/1368
- Updated RequireScreeningModal to include the Calendly widget
- Added matomo tracking events
> feat: Add CalendlyWidget on the RequireScreeningModal

- src/pages/pupil/Group.tsx
- src/pages/student/StudentGroup.tsx
Quick-temp fix for https://github.com/corona-school/project-user/issues/1381
- Increase limit to 50 for the subcoursesPublic Query
A proper pagination will be implemented in a separate task
> fix: Increase limit for subcoursesPublicQuery

- src/widgets/screening/ScreenPupilCard.tsx
- The new restrictions were temporarily removed to create a pupil screening (subjects/grade/language) as required.
- Error message is still shown so Screeners know that they should as for those, but they can create the screening, so this doesn't break they workflow anymore
- This will be improved with the UI Facelift coming soon
> fix: Remove new create SuS screening restrictions

- src/widgets/ImportantInformation.tsx
Updated logic to create a screening link, so that screeing link is not created/sent, if student has already a tutor or instructor role:
(stud.canCreateCourse= 'not-screened' && stud.canReqMatch = 'not-screened') ||
(stud.canCreateCourse = 'not-instructor' && stud.canRequestMatch = 'not-screened') ||
(stud.canCreateCourse = 'not-screened' && stud.canReqMatch = 'not-tutor') ||
(stud.canCreateCourse = 'not-instructor' && stud.canReqMatch = 'not-tutor')
Resolves corona-school/project-user#1042
> fix: hide info if already screened

- src/components/Panels.tsx
- src/pages/screening/pupil/PupilDetail.tsx
- src/pages/screening/student/StudentDetail.tsx
- Added a new `inactiveMode` prop to control how should the tabs behave when not active
- Updated the tabs in the screening tool to use the `hide` mode
> Fix: Tabs inactive behavior for new screening tool

- src/lib/WebPush.ts
Accessing sw.pushManager.(some method) failed
> fix: PushManager does not exist on older devices

- src/pages/create-appointment/AppointmentAssignment.tsx
Resolves https://github.com/corona-school/project-user/issues/1392
- Filter out canceled courses on the create appointment View
> Fix: Filter out canceled courses from create appointment view

- package-lock.json
- package.json
- src/pages/course-creation/CourseAttendees.tsx
- src/pages/student/matching/SchoolClasses.tsx
Resolves https://github.com/corona-school/project-user/issues/1424
- Removed `react-native-slider` package
- Updated grade sliders to use our slider component which already allows single-value selection
> Feat: Allow single grade selection

- src/components/achievements/modals/AchievementModal.tsx
I'm not sure if there is any other impact, but it solves the problem. Fixes: https://github.com/corona-school/project-user/issues/1408
Before:
After:
> fix: achievement modal size on safari

- src/pages/pupil/SingleCoursePupil.tsx
- src/pages/pupil/single-course/PupilCourseButtons.tsx
- src/pages/student/SingleCourseStudent.tsx
- src/pages/subcourse/OpenCourseChatButton.tsx
Resolves https://github.com/corona-school/project-user/issues/1435
**On the pupil course detail page:**
- Use next appointment to enable `VideoButton`
- Hide chat button for pupils if chat is disabled
**On the student course detail page:**
- `VideoButton` is not enabled on time
> Fix: Join video button disabled state

- src/pages/student/MatchingStudent.tsx
Resolves https://github.com/corona-school/project-user/issues/1417
- Fixed `Zu den Bescheinigungen` button to navigate to `/certificates` instead of `/profile`
> fix: To the certificates button link

- src/components/HeaderCard.tsx
- src/components/notifications/NotificationAlert.tsx
- src/modals/LeavePageModal.tsx
- src/service-worker.ts
Resolves https://github.com/corona-school/project-user/issues/1450
- Add a `showNotifications` query param, that opens the notifications popover
- Append the new parameter after clicking a push notification
> Feat: Show notifications popover after clicking a Push notification

- src/pages/Appointment.tsx
- Added `isParticipant` in the appointmentPupil query to be able to show the `Termin absagen`-Button
> fix: Include isParticipant in the appointmentPupil query

- src/pages/create-appointment/AppointmentsInsight.tsx
When creating a new appointment, in the second step, existing appointments aren't shown _(even if there are)_
- Updated the styles on the AppointmentInsights step to show the AppointmentList correctly
> Fix: Show appointment list when creating a new appointment

- src/pages/CreateCourse.tsx
- src/pages/course-creation/CoursePreview.tsx
- src/pages/screening/single-course/ScreenerCourseButtons.tsx
- src/pages/student/single-course/StudentCourseButtons.tsx
- Fixed the naming & usage of the courseId and subcourseId on the CreateCourse page. It seems we were using them interchangeably, and it was causing issues on Production _(since there, they are not the same, unlike on STG where they happened to be the same for all courses)_
> fix: Naming & usage of courseId/subcourseId on the CreateCourse page

- src/pages/screening/student/ScreenStudent.tsx
- Made the `jobStatus` and `knowsUsFrom` fields optional for HuH screenings.
> fix: Make jobStatus / knowsUsFrom fields optional

- src/pages/screening/Dashboard.tsx
- src/pages/screening/components/ButtonField.tsx
- src/pages/screening/components/KnowsUsSelect.tsx
- src/pages/screening/student/ScreenStudent.tsx
- src/pages/screening/student/StudentHistory.tsx
- src/types/index.ts
Resolves https://github.com/corona-school/project-user/issues/1486
- Updated the UI of Student screenings to show pending screenings and allow updates
- Included an `Aktuell nicht interessiert` button to discard a screening
- Updated the mutations according to new backend convention for student screenings
> Feat: Allow student screening statuses

- src/pages/CalendarPreferencesPage.tsx
- Fixed an invalid default value for calendar preferences on the frontend, that could cause a backend validation error if attempted to save
> fix: Remove empty object for calendar preferences default value

- src/pages/pupil/Dashboard.tsx
- src/pages/pupil/Matching.tsx
Updated logic to enable Create match request button for pupils when a subject is not selected.
> fix: When match request button is disabled

- src/pages/screening/Dashboard.tsx
- Added missing fields when fetching pupils from disputed screenings
> fix: Add missing fields for disputed screenings

- src/pages/pupil/SingleCoursePupil.tsx
- src/pages/pupil/single-course/PupilCourseButtons.tsx
- src/pages/student/SingleCourseStudent.tsx
Frontend part of https://github.com/corona-school/backend/pull/1266
- Updated subcourse appointments query to use `joinedAppointments` or `appointments` depending if the user is a participant/instructor of the course
> fix: Use joinedAppointments for course participants/organizers

- src/pages/ResetPassword.tsx
Resolves https://github.com/corona-school/project-user/issues/1527
Don't render `WithNavigation` on a public page because it tries to use authenticated things only... This is a temporary fix because this page will change very soon.
> fix: Forgot password flow
